name: documentation

on:
  release:
    types: [created]

jobs:

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt install texlive-latex-base texlive-latex-recommended texlive-latex-extra latexmk make
        pip install ./qoqo-qryd
        python -m pip install -r ./userdoc/requirements.txt
    - name: build
      run: |
        cd ./userdoc
        make html
        make html
        make latex
        cd _build/latex/
        make
        cd ..
        mkdir pdf/
        cp latex/main.pdf pdf/
        cd ../
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./userdocumnentation/_build/html/

  publish_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        default: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip maturin
        pip install ./qoqo-qryd
        python -m pip install -r qoqo_qryd/userdoc/requirements.txt
    - name: build
      run: |
        cd qoqo_qryd/userdoc
        python -m sphinx -T -E -b html . _build/html
        cd ../../
    - name: publish
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./qoqo_qryd/userdoc/_build/html/