name: ci_tests_pull_request

on:
  pull_request:
    branches: [main]

jobs:
  linting:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_linting_rust_pyo3.yml@main

  unittests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_unittests_rust_pyo3.yml@main
    with:
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: false
      rust_package_name: "roqoqo-qryd"
      test_code_coverage: false
  
  build_tests:
    uses: HQSquantumsimulations/reusable_workflows/.github/workflows/reusable_build_tests_rust_pyo3.yml@main
    with: 
      # Run tests also on windows runners
      windows: true
      # Run tests also on macos runners
      macos: false
      py_interface_folder: "qoqo-qryd"
      has_python_tests: false

