name: test workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

env:
  API_DEV: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: TEST
      run: echo "$API_DEV"

