name: test workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  test-allowed-to-fail:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      QRYD_API_DEV: 0
    steps:
    - name: TEST FAILURE
      run: |
        echo "$QRYD_API_DEV"
        exit 1
    - name: CONTINUING
      run: echo "$QRYD_API_DEV"

  test-not-allowed-to-fail:
    runs-on: ubuntu-latest
    env:
      QRYD_API_DEV: 1
    steps:
    - name: TEST SUCCESS
      run: echo "$QRYD_API_DEV"
