name: Manual deploy

on:
  workflow_dispatch:

jobs:
  deploy_cratesio:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        default: true
    - name: setup cargo
      run: |
        cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
        cargo publish --manifest-path=roqoqo-qryd/Cargo.toml
        sleep 30
        cargo publish --manifest-path=qoqo-qryd/Cargo.toml